### ISSUE TITLE
Error when opening .js file in neovim

### ISSUE THREAD

**Issue by Meilky** [kyoz/purify#5] opened 2020-11-05 02:07 UTC
Hi,

I have a little problem when I open a .js file in neovim. It give me this error : 

```
Error detected while processing function <SNR>19_overwrite_javascript_highlight:
line    1:                                                                                                                                                    
E28: No such highlight group name: javaScriptIdentifier
```

Thank you for your time, your theme is awsome ;)

**Comment by Meilky** [comment] 2020-11-05 02:49
Update,

I comment line 367 in *purify/vim/colors/purify.vim* and the error stop show up.
Just like this :
```vim
function! s:overwrite_javascript_highlight()
    " syn clear javaScriptIdentifier
    syn clear javaScriptReserved
    call s:hi('javascriptEndColons',         { 'fg': s:pink })
    call s:hi('javascriptLogicSymbols',      { 'fg': s:salmon })
    call s:hi('javascriptOpSymbols',         { 'fg': s:pink })
    call s:hi('javascriptLabel',             { 'fg': s:pink, 'styles': [s:styles.italic] })
    call s:hi('javaScriptThis',              { 'fg': s:blue, 'styles': [s:styles.italic] })
    call s:hi('javaScriptCustomIdentifier',  { 'fg': s:green, 'styles': [s:styles.italic] })
    call s:hi('javaScriptCustomReserved',    { 'fg': s:blue, 'styles': [s:styles.italic] })
endfunction
```

**Comment by kyoz** [comment] 2020-11-05 03:26
Hello @Meilky , Thank you for your response, for improvement purpose, can you provide me more info about your setup. Like do you use vim, neovim, what's your os, plugins, etc...

Currently, i'm using latest neovim with coc for autocomplete, if you haven't use coc, you should give it a try. With coc you'll have fully autocomplete of almost all language & filetype with just few lines of config. And as it's just one plugin for all language completion, it'll help us avoid conflict with other plugins :smile_cat: 

This is my currently [config](https://github.com/kyoz/neovim/blob/master/configs/autocomplete.vim) with coc.

Thank you so much

**Comment by Meilky** [comment] 2020-11-09 19:49
Hello @kyoz , I use neovim 0.4.4 with coc (latest) as autocomplete and I run on Kali-linux 2020.3.
For my coc.vim config, I use the one from the [readme](https://github.com/neoclide/coc.nvim) of coc.
here is my coc-config.json:
```json
{
	"coc.preferences.formatOnSaveFiletypes": [
		"javascript",
		"typescript",
		"typescriptreact",
		"json",
		"html",
		"javascriptreact",
		"typescript.tsx",
		"graphiql",
		"css"
	],

	// prettier config
	"prettier.useTabs": true,
	"prettier.tabWidth": 4,
	"prettier.trailingComma": "all",
	"prettier.printWidth": 100,

	// suggest config
	"suggest.enablePreselect": true,
	"suggest.noselect": false,

	// python config
	"python.linting.enabled": true,
	"python.linting.pylintEnabled": true,

	"snippets.ultisnips.directories": ["UltiSnips", "~/.config/nvim/utils/snips"]
}
```

And, I don't know if it's the right place to put that but it would be awsome to have your theme for [ranger](https://github.com/ranger/ranger).
Ranger have a extention for nvim and it's call [rnvimr](https://github.com/kevinhwang91/rnvimr).

I would love to have your theme for rnvimr, the default theme suck compare to your's ;).

**Comment by kyoz** [comment] 2020-11-10 10:34
Hi @Meilky ,

For this issue, i'v tried to reproduce it on my devices but it doesn't occur.

That `javaScriptIdentifier` is neovim default Identifier, i'v checked their source code, it's still there. Maybe there'r some conflict with other plugins which i don't know.

Just leave this issue there, i'll dig to it when i have time.

As of `ranger`, i'v implement a very basic of Purify Colorscheme for it. You can install it [here](https://github.com/kyoz/purify/tree/master/ranger). It work while well for now.

But for `rnvimr`, as the author say, it take default colorscheme of ranger, but when i open it, it look weird. I'll take a look into this plugin when i have time. :cat:

**Comment by Meilky** [comment] 2020-11-10 15:43
Hello @kyoz ,

Here is my full [neovim config](https://github.com/Meilky/nvim-config) if it could help you.

Thank for the ranger theme, I love it.

**Comment by Puh00** [comment] 2020-12-14 15:40
I'm also receiving the same error messages as Meilky. Commenting out the  `syn clear javaScriptIdentifier` seems to resolve the issue for now. 
* neovim version 0.5.0

**Comment by kyoz** [comment] 2020-12-15 07:29
Hi @Meilky , @Puh00 , i'v looked into your configs and find out the problem.

Somehow, this is the conflict with 'vim-polyglot' plugin.

With Purify, i want to use the core syntax support by Vim & Neovim to ensure the best performance when coding.

Vim & Neovim are already support almost all programming language which exist on this world, what they missing is just a better colorscheme, Purify is what it's for. You can see what language neovim support by runtime syntax [here](https://github.com/neovim/neovim/tree/master/runtime/syntax)

I'v fixed this issue by silent the warning, you can now using vim with polyglot and purify normally, but if you are using neovim, i t hink you don't need polyglot cause neovim already have syntax for almost all language exist.

Just update Purify with `:PlugUpdate` and let me know if it work.

:cat:

**Comment by Puh00** [comment] 2020-12-15 23:50
Hi @kyoz,
Yes, it seems like the latest patch has resolved the issue. 

I wasn't aware that Neovim already supported so many languages. So what you are saying is that it is meaningless to have vim-polyglot for Neovim? Was the plugin primarily made for the "original" vim (who I assume did not have this feature)?

Thanks for the update.

**Comment by kyoz** [comment] 2020-12-16 01:58
Yes @Puh00 , vim and neovim by default have their runtime syntax, neovim syntax is a little bit better but they are just the same.

This is neovim (left), and vim (right) running on my machine. Vim just only install Purify as plugin.

![image](https://user-images.githubusercontent.com/29815830/102294608-46b9ac00-3f7c-11eb-9f43-cb1f453d73e2.png)

Vim polyglot is good but it's kind of heavy, i just install what language doesn't have syntax support yet, like typescript...It help Vim/Neovim running fastest as possible. :smile:

**Comment by kyoz** [comment] 2021-03-08 06:52
So this issues seem fixed since last patch. I'll close it then.

If you have any question or problem when using purify please open new issue :heart:

**Closed as completed by kyoz** 2021-03-08 06:52 UTC
